### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by ondrejhanslik** [nicorichard/SwiftGenPlugin#1]
Creating artifact bundle is something you have to do manually. The format is specified in https://github.com/apple/swift-evolution/blob/main/proposals/0305-swiftpm-binary-target-improvements.md
There is nothing complicated about it, it's just a folder structure with a manifest.

The problem with tagging is also a simple one. The ideal solution would be to use two separate packages (git repositories) - one with the tool and one with the plugin. I don't like it either, but it seems to be the simplest solution.

Regarding cleanup, I think you should:
1. parse `swiftgen.yml`
2. generate the list of input & output files
3. use `buildCommand` instead of `prebuildCommand`.

I am pretty sure that clean up will be handled automatically then.

**Comment by nicorichard** [comment]
Thank you for your help! I think I've resolves everything but the cleanup now.

I've also been able to put up a PR to SwiftGen itself https://github.com/SwiftGen/SwiftGen/pull/926
